package acz.ui;

import acz.analyzer.AttrClustAnalyzer;

public class CatDepResults extends javax.swing.JPanel {
    private AttrClustAnalyzer analyzer;
    
    /**
     * Creates new form CatDepResults
     */
    public CatDepResults(String classVal, AttrClustAnalyzer analyzer) {
        initComponents();
        
        this.analyzer = analyzer;
        this.jLabel_class.setText(classVal);
        this.jLabel_numClassInst.setText(
                String.valueOf(analyzer.getNumInstancesForClassValue(classVal)));
        initCatDepResultsView(classVal);
    }
    
// =======================================================================================
// --=========================== Helper Methods ========================================--
// =======================================================================================
    
    private void initCatDepResultsView(String classVal) {
        jTable_classDepStats.setModel(new ClassDepStatsModel(classVal, analyzer));
    } 
    
// =======================================================================================
// =======================================================================================

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_classDepStats = new javax.swing.JTable();
        jLabel_class = new javax.swing.JLabel();
        jLabel_numClassInst = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setText("CLASS SPECIFIC RESULTS");
        jLabel3.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Class:");
        jLabel2.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Number of Class Instances:");
        jLabel4.setToolTipText("");

        jTable_classDepStats.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_classDepStats);

        jLabel_class.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_class.setText("class");
        jLabel_class.setToolTipText("");

        jLabel_numClassInst.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel_numClassInst.setText("numClassInst");
        jLabel_numClassInst.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                        .addGap(392, 392, 392))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_class)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_numClassInst)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel_class))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel_numClassInst))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_class;
    private javax.swing.JLabel jLabel_numClassInst;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_classDepStats;
    // End of variables declaration//GEN-END:variables
}
